name: CI Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI
    inputs:
      run_tests:
        description: 'Run tests (if available)'
        required: false
        default: true
        type: boolean
      build_sample:
        description: 'Build sample project'
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore package/CQRS.csproj
      
    - name: Build
      run: dotnet build package/CQRS.csproj --configuration Release
        
    - name: Verify package contents
      run: |
        echo "Created packages:"
        ls -la ./test-nupkgs/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: github.event_name == 'push'
      with:
        name: build-artifacts-${{ github.sha }}
        path: |
          ./test-nupkgs/
          package/bin/Release/
        retention-days: 7