name: CI Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore package/CQRS.csproj
      
    - name: Build
      run: dotnet build package/CQRS.csproj --configuration Release --no-restore
      
    - name: Build Sample
      run: dotnet build sample/CQRS.Sample.csproj --configuration Release --no-restore
      
    - name: Run tests (if any)
      run: |
        if [ -f "tests" ] || find . -name "*.Tests.csproj" -o -name "*Test*.csproj" | grep -q .; then
          dotnet test --configuration Release --no-build --verbosity normal
        else
          echo "No tests found, skipping test step"
        fi
        
    - name: Create test package (without publishing)
      run: dotnet pack package/CQRS.csproj --configuration Release --no-build --output ./test-nupkgs
      
    - name: Verify package contents
      run: |
        echo "Created packages:"
        ls -la ./test-nupkgs/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: github.event_name == 'push'
      with:
        name: build-artifacts-${{ github.sha }}
        path: |
          ./test-nupkgs/
          package/bin/Release/
        retention-days: 7